const questions = [
    {
        id: 1,
        answer: 'Hypertext Markup Language',
        category: 'HTML',
        question: 'What does HTML stand for?',
    },
    {
        id: 2,
        answer: '<!DOCTYPE html>',
        category: 'HTML',
        question: 'What should go at the top of every HTML page?',
    },
    {
        id: 3,
        answer: '<html>',
        category: 'HTML',
        question: 'What is the root element?',
    },
    {
        id: 4,
        answer: '<head> and <body>',
        category: 'HTML',
        question: 'What are the two main grouping elements that sit inside the HTML tags?',
    },
    {
        id: 5,
        answer: '<meta>, <title>, <link>, <script>',
        category: 'HTML',
        question: 'What are some tags you would likely find in the head element?',
    },
    {
        id: 6,
        answer: '<body> inside the body tags </body>',
        category: 'HTML',
        question: 'Where would you find all of the visible content that shows up on the screen?',
    },
    {
        id: 7,
        answer: 'Using <h1>, <h2>...<h6> tags <br> <h1>My Title</h1>',
        category: 'HTML',
        question: 'How would you create a header?',
    },
    {
        id: 8,
        answer: '<p> using p tags </p>',
        category: 'HTML',
        question: 'How would you create a paragraph?',
    },
    {
        id: 9,
        answer: '<ol> and <li> tags',
        category: 'HTML',
        question: 'How would you make a numbered list?',
    },
    {
        id: 10,
        answer: '<ul> and <li> tags',
        category: 'HTML',
        question: 'How would you make a bulleted list?',
    },
    {
        id: 11,
        answer: '<table>, <tr>, <th>, and <td>',
        category: 'HTML',
        question: 'What are the elements you need to build a table?',
    },
    {
        id: 12,
        answer: 'action and method <br> <form action="welcome.php" method="post">',
        category: 'HTML',
        question: 'What attributes does a form need?',
    },
    {
        id: 12.5,
        answer: 'method="POST"',
        category: 'HTML',
        question: 'What method should you use for private or sensitive information, like username and password?',
    },
    {
        id: 13,
        answer: '<input>, <textarea>, <select>',
        category: 'HTML',
        question: 'What form controls do you have access to for user input?',
    },
    {
        id: 14,
        answer: 'text, email, password, date, number, checkbox, radio, submit',
        category: 'HTML',
        question: 'What input types are available to use?',
    },
    {
        id: 15,
        answer: '<img src="boat.png" alt="boat on a lake" />',
        category: 'HTML',
        question: 'How do you display an image? ',
    },
    {
        id: 16,
        answer: 'Use the full or absolute URL <br><a href="https://www.cui.edu">CUI</a>',
        category: 'HTML',
        question: 'How do you create a link to another site?',
    },
    {
        id: 17,
        answer: '<a href="https://www.cui.edu" target="_blank">CUI</a>',
        category: 'HTML',
        question: 'How do you open a link in another tab?',
    },
    {
        id: 18,
        answer: '<a href=”https://www.google.com#middle>Middle of google page</a>',
        category: 'HTML',
        question: 'How do you link to a specific section of a page?',
    },
    {
        id: 19,
        answer: 'Cascading style sheet',
        category: 'CSS',
        question: 'What does CSS stand for?',
    },
    {
        id: 20,
        answer: 'p { color: red; }',
        category: 'CSS',
        question: 'How do you select all p tags and color them red?',
    },
    {
        id: 21,
        answer: 'p#first-paragraph {}',
        category: 'CSS',
        question: 'How do you select a p element with an id of ‘first-paragraph’?',
    },
    {
        id: 22,
        answer: 'p.red { color:red; }',
        category: 'CSS',
        question: 'How do you select all p elements with a class of red',
    },
    {
        id: 23,
        answer: 'div p {}',
        category: 'CSS',
        question: 'How do you select a p tag that is inside a div?',
    },
    {
        id: 24,
        answer: 'background-color, color, display, height, width, margin, padding, position, box-sizing, border, border-radius, etc.',
        category: 'CSS',
        question: 'What are some common styles?',
    },
    {
        id: 25,
        answer: 'You can assign color by color name, hex #, rgb, rgba, hsl, hsla',
        category: 'CSS',
        question: 'What are the different types of color values you can use in your CSS?',
    },
    {
        id: 26,
        answer: 'A way to set styles based on a condition, such as screen width or height',
        category: 'CSS',
        question: 'What is a media query?',
    },
    {
        id: 27,
        answer: '@media only screen and (max-width: 786) {<br>...styles here...<br>}',
        category: 'CSS',
        question: 'How do you add styles for devices with a screen width of less than 786px?',
    },
    {
        id: 28,
        answer: 'A script is a series of tasks to complete a goal',
        category: 'JS',
        question: 'What is a script?',
    },
    {
        id: 29,
        answer: 'You can write JavaScript between <script> tags, but it is best practice to write it in a separate js file (index.js)',
        category: 'JS',
        question: 'Where do you write your JavaScript?',
    },
    {
        id: 30,
        answer: 'Script tags can be placed anywhere in the head or body, but are often placed just before the closing </body> tag.',
        category: 'JS',
        question: 'Where do you put your script tags?',
    },
    {
        id: 31,
        answer: '<script src="index.js"></script>',
        category: 'JS',
        question: 'How do you import an external JavaScript file',
    },
    {
        id: 32,
        answer: 'A way to store data',
        category: 'JS',
        question: 'What is a variable?',
    },
    {
        id: 33,
        answer: 'Use var, let, or const <br> var myName = "Brian"',
        category: 'JS',
        question: 'How do you declare a variable?',
    },
    {
        id: 34,
        answer: 'A string, number, or boolean value',
        category: 'JS',
        question: 'What datatypes can be stored in a variable?',
    },
    {
        id: 35,
        answer: 'An array, object, and reference to a Node on the DOM (in the form of an array or object)',
        category: 'JS',
        question: 'Besides strings, numbers and boolean values, what else can we store in a variable?',
    },
    {
        id: 36,
        answer: 'Variables declared inside a function are not accessible outside the function.<br> Variables declared at the global level can be accessed within functions.',
        category: 'JS',
        question: 'What is variable scope?',
    },
    {
        id: 37,
        answer: 'A way to organize code into reusable blocks',
        category: 'JS',
        question: 'What is a function?',
    },
    {
        id: 38,
        answer: 'Function sayHello() {...code block...}',
        category: 'JS',
        question: 'How do you declare a function?',
    },
    {
        id: 39,
        answer: 'You call a function by it\'s name, followed by () <br> sayHello()',
        category: 'JS',
        question: 'How do you call a function?',
    },
    {
        id: 40,
        answer: 'Var sayHello = function() {<br>...code block...<br>}',
        category: 'JS',
        question: 'What is an anonymous function?',
    },
    {
        id: 41,
        answer: 'By adding parenthesis at the end of the code block.<br>Var sayHello = function() {...code block...}()',
        category: 'JS',
        question: 'How do you write an immediately invoked function expression (IIFE)?',
    },
    {
        id: 42,
        answer: 'Parameters are variables used in functions and methods. You can add parameters inside the parenthesis when declaring a function. function sayHello(name) { alert(\'hello \' + name) }',
        category: 'JS',
        question: 'What are parameters and how are they used?',
    },
    // {
    //     id: 43,
    //     answer: '',
    //     category: 'JS',
    //     question: '',
    // },
];

export {questions};